# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

lane :build_for_pr do
  gym(
    scheme: "YourAppScheme",  # Change to your actual scheme
    destination: "generic/platform=iOS Simulator", 
    export_method: "development",  # No signing required
    skip_codesigning: true
  )
end
